### ISSUE TITLE
Lil error.

### ISSUE THREAD

**Issue by K0-RR** [PalgamingHD/Prehistoric#2]
[main/WARN]: Reference map 'Prehistoric-refmap.json' for mixins.prehistoric.json could not be read. If this is a development environment you can ignore this message

**Comment by K0-RR** [comment]
And this:
[Worker-Main-2/WARN]: Unable to load model: 'prehistoric:block/analyzer_active' referenced from: prehistoric:analyzer#facing=north,lit=true: java.io.FileNotFoundException: prehistoric:models/block/analyzer_active.json

**Comment by K0-RR** [comment]
And this:
[Worker-Main-2/WARN]: Texture prehistoric:block/chest1 with size 10x9 limits mip level from 4 to 0

**Comment by PalgamingHD** [comment]
Yea ignore all those, the first one is because I dont have any mixins, the second one is because I turned off the feature where the analyzer has a lit blockstate, and the 3rd is might be something I have to fix but i'll check. But it should run fine even with the errors

**Comment by K0-RR** [comment]
> the first one is because I dont have any mixins

Then please delete mixins.prehistoric.json and the mention of it from the fabric.mod.json. I'm fighting for cleaner logs.

**Comment by PalgamingHD** [comment]
Alright I'll see if I can fix the other two warnings
